### ISSUE TITLE
"Failed to start add-on Macros: Cannot find module 'sqlite3'

### ISSUE THREAD

**Issue by madb1lly** [Galveston01/macrozilla#6]
Hi @Galveston01,

I couldn't find you on the #iot channel so I'm raising this issue, but the fix might be simple and I might be being daft! So please excuse me if that's the case.

I installed this new add-on (which looks great!) and added the token to it. When I go to the Macros page and try to add a new one this message pops up at the bottom: "Failed to start add-on Macros: Cannot find module 'sqlite3'

It only comes up once. It closes when I close the Name dialogue box which pops up. To make it appear again I need to change the settings for the add-on.

I can't create any macros or variables. Please let me know what I need to do to fix this or what further testing I should do.

Cheers 🙂

**Comment by blumenkoehlchen** [comment]
I got the same issue.

**Comment by Galveston01** [comment]
Hello there,
Yeah, turns out that in the release v0.1.4 a dependency was missing. Didn't notice that in the first place, so thanks for the hint. New release v0.1.5 is building right now and should hopefully appear on the add-on list quickly thereafter.

**Comment by madb1lly** [comment]
Hi @Galveston01,
Excellent, it's working now!
Cheers 🙂
