### ISSUE TITLE
Multiple Email Senders share subject text

### ISSUE THREAD

**Issue by cncb-gh** [Galveston01/macrozilla#75]
I have an IF/ELSE block where I send emails with different subjects based on the condition.  When I edit the subject text for one of the Send Simple Email actions, when I save the macro and reopen it, the subject text for the other was modified to be the same.  So, it seems they are sharing the same text instead of being independent.  I tried to work around this by creating a Variable for the subject text, but I can't figure out how to use the variable as the actual subject text?

**Comment by bewee** [comment]
Hi @cncb-gh,

I suppose you use some sort of email addon? Could you tell me which addon this is?

Also, it would be great if you could attach a screenshot of the macro which causes you problems.

Concerning the variable, it's actually a downside of the current implementation that it is not possible to parameterize action input (like, in your case, email subject) using e.g. variables. PRs always welcome :)

Regards!

**Comment by cncb-gh** [comment]
It is the "Email Sender" addon supplied by the WebThings team.  Here is a screenshot of a test macro.  I specified "FIRST" as the first subject, saved the macro, went back and returned to the macro and now it shows "SECOND" for the subject.
![macro](https://user-images.githubusercontent.com/8257394/138291402-9ab1524f-50f3-4416-a3cb-e89488ae9e99.JPG)
.

**Comment by bewee** [comment]
Will have a look at and try to reproduce it. It may take a few days, as I no longer actively use this addon myself (switched all my automation to [node red](https://github.com/bewee/node-red-extension) a while ago as it is more powerful)

**Comment by bewee** [comment]
@cncb-gh  I was able to reproduce the described bug using virtual things. #79 fixes it on my machine. Could you checkout the linked branch and tell me whether this fixes it for you as well? Thanks :)

**Comment by cncb-gh** [comment]
Sorry, can you please tell me how to checkout the branch on my Pi?  Since it was just 1 line added, I tried to edit the file (nano) via ssh and now it won't load.  I tried to edit the file again and take out the added line and it still doesn't work.  Trying to re-install the addon is also failing.  Thanks.

**Comment by bewee** [comment]
@cncb-gh Right, with just one line changed, copy-and-paste may be easier than learning git😅
Problem is that the add-on is shipped with a checksum which the files are checked against during addon loading. You can prevent this by creating a folder called ".git" in the addon directory.

**Comment by cncb-gh** [comment]
I was able to confirm that this allows for independent subjects in multiple email messages in one macro.  Thanks so much for working on this even though you do not use it anymore!
