### ISSUE TITLE
Cannot set decimal/float numbers for Thermostat

### ISSUE THREAD

**Issue by cncb-gh** [Galveston01/macrozilla#76]
I am trying to set cooling and heating set points for my Z-Wave thermostat.  It appears that it requires Celsius values so I need to use decimal/float numbers in the Set block.  I have tried using "number" and "text" values and "as number" values but it only works if I supply an integer.  I know it is not working because the Thermostat display shows a message about setting the temperature, but the set point never changes (an integer causes the set point to change).  Normal Rules work for the setpoints, but it would be nice to have the option to do it in a Macro as well.

![wt_thermo](https://user-images.githubusercontent.com/8257394/138471952-f0645aa9-c549-4cbd-9089-5b87015f55bc.JPG)

**Comment by bewee** [comment]
Hi @cncb-gh,

thank you for your bug report. Only had a quick look at your issue and saw that z-wave thermostats require multiples of 0.5: https://github.com/WebThingsIO/zwave-adapter/blob/85cacaa53b80464143c1455e61b734c5c9697c93/zwave-classifier.js#L895
Does it happen to work if you supply values which are a multiple of 0.5?
Besides this, could you please post a relevant portion of the internal logs? That may help a lot :)

Regards!

**Comment by cncb-gh** [comment]
Sorry, I should have noticed that the normal Rules were "rounding" to the nearest .5.  It works fine when I do this in the Macro too.  Thanks for this great addon.

**Comment by bewee** [comment]
Nothing to be sorry about. It is definitely not intended to fail without any notice and this behaviour should be changed. Rounding sounds like a sensible solution and is most likely what macrozilla should do as well.
