### ISSUE TITLE
Drag and drop to trash creates sprites

### ISSUE THREAD

**Issue by flatsiedatsie** [Galveston01/macrozilla#9]
First of all: wow! What a cool addon!

I did run into a small bug. I dragged an element in to the main area, and then dragged it back to the sidebar to delete it. This can create strange behaviour where the element seems to visually persist in the sidebar.

![macros_drag-bug](https://user-images.githubusercontent.com/805405/94777764-4b7eb300-03c4-11eb-91e2-dd028411924f.png)

**Comment by Galveston01** [comment]
Hi, 

Thanks for reporting this issue. Could you please checkout [this](https://github.com/Galveston01/macrozilla/tree/deleteonmouseup) branch and tell me whether the problem is solved there?

**Comment by Galveston01** [comment]
Latest release should have solved this
